### PR TITLE
S-95141:Added new workflows - secrets and terraform

### PR DESCRIPTION
**Pull request by nitheshrayuduv**
S-95141:Added new workflows - secrets and terraform

### CODE REVIEW

**Review by mayur9991 — APPROVED** [review]
@nitheshrayuduv Please look at changes I made to avoid such mistakes in future.

**Comment by nitheshrayuduv** [comment]
Thanks @mayur9991  for the review, we will make sure to follow the above standards and avoid those mistakes.

**Comment by nitheshrayuduv** [comment]
Got the below error while trying to get the workflow/0.0.6 , 

image

We are looking into the same.

**Comment by mayur9991** [comment]
@nitheshrayuduv There are no issues. I have verified. You need latest changes from master on xl-release repo.

**Comment by nitheshrayuduv** [comment]
Ahh got it, we were testing with beta6 , we will test with the latest nightly/build from latest xl-release repo :) Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
